### ISSUE TITLE
Singleton JVM

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#122]
We only support singleton interaction with the JVM (unless we address https://github.com/dart-lang/jnigen/issues/121).

We should

- [ ] rename Jni.spawn to Jni.singleton (or a better name)
- [ ] Add a mutex around JVM initialization
- [ ] Add a mutex around any other initialization https://github.com/dart-lang/jnigen/issues/85

**Comment by mahesh-hegde** [comment]
Actually creation of multiple JVMs is not supported even in the standard JDK.

you get JNI_EEXIST if you try to spawn a second JVM.

So I don't think we need a lock here. Just have to catch JNI_EEXIST.

`spawn()` can remain. It doesn't return JVM.

**Comment by HosseinYousefi** [comment]
Closing then.
