### ISSUE TITLE
Define primitive types (`JBoolean` etc) manually

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#124]
In https://github.com/dart-lang/jnigen/pull/118 creating an array of booleans is:

```dart
final array = JniArray(const JniBooleanType(), 3);
```

However, we would prefer

```dart
final array = JniArray(JBoolean.type, 3);
```

However, `JBoolean` is defined in in `jni.h` as a typedef, which is then translated to Dart:

```dart
typedef JBoolean = ffi.Uint8;
typedef JByte = ffi.Int8;
typedef JChar = ffi.Uint16;
typedef JShort = ffi.Int16;
typedef JInt = ffi.Int32;
typedef JLong = ffi.Int64;
typedef JFloat = ffi.Float;
typedef JDouble = ffi.Double;
```

Instead of leaking these typedefs to the user, we should rename them in our ffigen config, and instead define `JBoolean` (and the others) ourselves, so that we can define a `.type` static getter that returns `JniType<JBoolean>`.

TODO:

- [ ] Check if this causes problems somewhere else. E.g. when we start generating code for callbacks and we have to deal with function signatures, do we cause problems for ourselves because those signatures would have the typedefs instead of our own type hierarchy?
- [ ] Check if it would be useful to introduce a `JPrimitive` that these 8 types implement.

**Comment by mahesh-hegde** [comment]
> Check if this causes problems somewhere else. E.g. when we start generating code for callbacks and we have to deal with function signatures, do we cause problems for ourselves because those signatures would have the typedefs instead of our own type hierarchy?

Somewhere there can be code that generates `JObject` which then would have to be changed to `ffi.Pointer<ffi.Void>`. But that's not a big issue.

But this is double edge sword, because someone familar with JNI C API would expect `JObject` to be a `Pointer<Void>`

**Comment by mahesh-hegde** [comment]
> If we're going to have Dart/Flutter developers who don't know any C use the Android libraries.

Makes sense, but there may be some performance oriented users too.

If object overhead in Dart matters, then one shouldn't be calling JNI in loop either. Move some compute logic to java and keep the glue minimal.

But there may be use cases I can't think of.
