### ISSUE TITLE
Rename `JniX` to `JX`

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#125]
Motivation is to write shorter code, also java types are called `jint`, `jobject`, ... in C, which makes it familiar for people who have some experience with JNI.

**Comment by mahesh-hegde** [comment]
Depends on whether you want direct access somewhere to APIs of `_env`.

They currently preserve FFI/C meaning, and higher level wrappers are called `JniX`.

**Comment by HosseinYousefi** [comment]
I think we should slowly move away from exposing the `env` and such to end-users.

**Comment by mahesh-hegde** [comment]
> I think we should slowly move away from exposing the env and such to end-users.

In the meanwhile though, there are lot of things which can only be done through `env`.

Call nonvirtual method, byte buffer, and bunch of other abstractions.
