### ISSUE TITLE
Add tests for `JArray<JObject>`

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#128]
Please add tests with `JArray<JObject>`.

_Originally posted by @dcharkes in https://github.com/dart-lang/jnigen/pull/126#discussion_r1017849505_

**Comment by HosseinYousefi** [comment]
Would be better to test once we create some form of casting like `obj.cast<JString>` to actually check for equality of different values in the tests.

**Comment by dcharkes** [comment]
Hm, then how do we know right now that our API works? 🙃

**Comment by HosseinYousefi** [comment]
`JString` and all other object arrays redirect everything except `operator []` to `JArray<JObject>`. I could add a small test to check that initially array of objects is null and length is the correct length.

**Comment by HosseinYousefi** [comment]
Will track this in #55. Closing.
