### ISSUE TITLE
naming: delete vs release

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#131]
We have `delete`, `deleteIn` and in https://github.com/dart-lang/jnigen/pull/130 `deleteOriginal`.

"delete" refers to deleting the **handle** that holds on to the Java object (`DeleteGlobalRef`).

However, the method is on an object representing a Java object. And we're not actually deleting any Java objects. Instead, we're letting go of the Java object.

Someone using our API does not know about handles, they just know that we are "referring" to a Java object (`JReference`).

So, we should consider renaming "delete" to something that signals we're no longer holding on, no longer referring to the Java object. For example "release". You release the object, the opposite of holding on. (Or maybe the opposite of holding on would be "let go" but that is two words.) Or another option is we "forget" about the Java object, but that seems like we're in control of what we're doing. So, "release"?

Some prior discussion: https://github.com/dart-lang/jnigen/issues/49#issue-1362986168

@mahesh-hegde I want to move more and more away from the JNI implementation details. 🙃
@HosseinYousefi what are your thoughts about this?

**Comment by mahesh-hegde** [comment]
> I want to move more and more away from the JNI implementation details. 🙃

Not to discourage you

https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/

😅

**Comment by HosseinYousefi** [comment]
> what are your thoughts about this?

I agree that `delete` is not be the best name for it.

**Comment by mahesh-hegde** [comment]
What's the status of this?

One issue I see is `release()` may be mistaken for all instances of that object, possibly obtained through different calls, being released. But they are all different JNI references with independent lifecycle.

**Comment by HosseinYousefi** [comment]
> One issue I see is `release()` may be mistaken for all instances of that object,

Same can be said about `delete`. We used to have `[obj release]` in Objective-C which meant let's just reduce the reference counter by one.

**Comment by HosseinYousefi** [comment]
Let's decide on this and #140 before 0.6.0 release.

Mandatory @lrhn tag.

Currently we have `javaObject.delete()` meaning that we want to let go of this **one** reference to the object, not to completely get rid of it. I personally feel like `release` captures this concept better. Any other ideas?
