### ISSUE TITLE
Dart equivalent of commonly used Java types

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#137]
We currently have `JString` which represents `java.lang.String`, and it's not a generated class. This is nice because we can add custom methods like `toDartString` and make the developer experience better. The support for other `java.lang.X` directly from JNI would be nice to have. For example `JInteger` -> `java.lang.Integer` that could have a `toDartInt` method.

This would mean that we need to come up with a different naming scheme to differentiate primitives and objects.

**Comment by mahesh-hegde** [comment]
> that could have a toDartInt method

In this case, `Integer` has `intValue()` method. But I get your point 😁 

I believe a more realistic approach will be enabling users to add extensions to the generated packages.

So if one day you generate `java.lang.Integer`, you create a file in `java/lang/` and add any extension methods there.

There's nothing theoretically preventing this approach today. But it's cumbersome.

You rather need a way to specify extension files, which may reside outside the output folder, to be exported from _package.dart files.

I believe this is a scalable approach. User can import `java/lang/_package.dart` and get `1.toJInteger()` from `java_stdlib` package.

**Comment by HosseinYousefi** [comment]
> So if one day you generate java.lang.Integer

That's the point, we don't want to generate that, since it's super common, so it could reside in `package:jni` itself. Similar to how we don't generate String.

What do you think about the naming though?

Right now we have `JArray<JBoolean>` to specify an array of primitive `boolean`s. But of course we also have `java.lang.Boolean`. We could have something like `JPrimitiveBoolean` and `JBoolean`. Any better idea?

**Comment by mahesh-hegde** [comment]
I think it's still better to be in a stdlib package, and implement the generated package interop mechanism (#72 ) to pass that to other libraries.

Do you have an application in mind which needs a greater level of integration?

**Comment by mahesh-hegde** [comment]
> What do you think about the naming though?

I think `JPrimitiveBoolean` is bit clunky, since it is being used more than `Boolean` reference type.

You may introduce a named import for these types, not sure if that's idiomatic.

**Comment by HosseinYousefi** [comment]
> I think `JPrimitiveBoolean` is bit clunky, since it is being used more than `Boolean` reference type.

I don't think that's necessarily the case. It's only really used in array type signatures.

> You may introduce a named import for these types, not sure if that's idiomatic.

Hmm, not sure about this one.

Maybe `JBoolean` for primitive ones and `JBoxedBoolean` for boxed ones. 

cc @dcharkes, what do you think?

**Comment by mahesh-hegde** [comment]
> JBoxedBoolean

This sounds good to me.

Since boxed type names are usually more verbose, you still have to make a choice, eg: `JBoxedInt` or `JBoxedInteger`? 

(Guess this one is matter of preference).

**Comment by HosseinYousefi** [comment]
> and implement the generated package interop mechanism (https://github.com/dart-lang/jnigen/issues/72 )

This sounds like a good thing to have even to implement this feature. I don't want to keep edge cases like how we do for `java.lang.String` and `java.lang.Object` currently.

**Comment by HosseinYousefi** [comment]
Wild idea:

`jint`, `jfloat`, ... for primitives and `JInteger`, `JFloat`, ... for boxed types!
