### ISSUE TITLE
Include JNI Java dependency on `jni:setup`

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#166]
Using JNI on Android is straightforward, as the java sources reside inside JNI's Android directory. This however is not the case for the standalone Dart projects, where the `.jar` file needs to be manually copied to the project. `bindings_writer.dart` should copy the `jni.jar` just as it copies `dartjni.h` to the `src/` directory of the new JNI project. The `.jar` file also needs to be built if it doesn't exist or the source has changed, similar to the APISummarizer in JNIgen.

**Comment by mahesh-hegde** [comment]
What do you refer to by `jni.jar`? Is it in the case custom `.java` files are used in standalone project?

**Comment by HosseinYousefi** [comment]
To support Kotlin coroutines, I added a support class called `PortContinuation` to `package:jni`. In standalone projects, this file need to be copied into the new projects and used there. See [`kotlin_test`](https://github.com/dart-lang/jnigen/tree/ec0b8aba28b673e18d7c04cd22dd69e0f4488cc2/jnigen/test/kotlin_test).

**Comment by mahesh-hegde** [comment]
I'd suggest renaming `cmake` folder in `jnigen/` to `assets`. We are going to see many this kind of files with #37 .

**Comment by HosseinYousefi** [comment]
This has been solved in https://github.com/dart-lang/jnigen/commit/c951f23ee6cfe7a823c45bc49dd3e3ffd95104e7#diff-5d579d061f6f7b79e6722500e378c3d2cc9f4078245b483ec39228a7a35637b7.
