### ISSUE TITLE
Context system & enabling use of JNI Local refs

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#185]
## Background

`jnigen` may benefit from a context system, which can

* Allow choosing between local references and global references - this is the main purpose

* Possibly handle multiple JVMs

* Destroy a JVM

* Remove need for global state in `package:jni` C layer, thus potentially making the library more reusable. Maybe someday if someone wants to write a Go equivalent of jnigen, `package:jni`s C code can be reused in it

To clarify more on last point, we have a bunch of different wrappers over functionality provided by `jni.h`, some in form of `GlobalJniEnv`, some in form of more sophisticated `Accessor` functions which check for and return JNI exceptions, and a bunch of ad-hoc functions which provide access to global state of the library (eg: Application context `jobject` on Android). It's not very elegant.

Related to #149 , we can hopefully implement a single set of JNIEnv wrapper functions which take the context and handle appropriately. This will also help to keep the large part of the code stable if, in future, we add more detail to the `context`.

## Implementation issues

1. __API for providing context__:
  * We need a way to pass context, which doesn't become repetitive.
  * Even if we store context in `JniObject`, all static functions and constructors are a potential entry point to JNI. It's easy to forget a context where it's required, since it's an optional argument.
  * We don't want a `setContext` style API which sets a default context globally, because JNI operations can be interleaved with async calls.

2. __API for local references__:
  * I am not sure if there should be a separate issue for this. Vyacheslav Agorov mentioned making use of `PushLocalFrame` & `PopLocalFrame` in a scoped fashion to handle local references efficiently. Wrapping that is an API similar to `using` will likely work as long as we aren't putting any async stuff in between.
  * Another option is to make the local vs global reference issue orthogonal, and provide it as a code generation time option in YAML. JNI APIs don't care if `JObject` is a local or global reference. So interop between bindings generated with different options should not be a problem.

3. Thread-local state

  * In C, we can't declare a `thread_local` struct member in context struct, for obvious reasons. It's indeed possible to get the same effect using `pthread_getspecific` and friends, but that might end up much slower than compiler allocated thread locals. We want to access JNIEnv every time we make the `Dart -> JNI` call, so we want compiler generated thread locals. That leaves us at either
    * limiting to 1 JVM (fine for most use cases)
    * using a critical section and a finite number of JVMs, with a thread local array declared globally?

Some references:

https://stackoverflow.com/questions/2459692/linuxs-thread-local-storage-implementation

https://stackoverflow.com/questions/32245103/how-does-the-gcc-thread-work

**Comment by mahesh-hegde** [comment]
@dcharkes any ideas regarding this?

Basically I am trying to find a design which lets us ergonomically use local references.

**Comment by dcharkes** [comment]
I discussed multiple JVM support recently with @HosseinYousefi, but currently we don't have any users asking for that.

But the other things you mention might be potential issues indeed. @HosseinYousefi I remember you mentioning something recently about contexts as well (maybe related to activities?) What are your thoughts?

I'd prefer not bloating the API for users if we can avoid it, but if we need to pass something as a context for correctness, we would have no choice. (You can also not use a Dart VM without knowing the 'context' of which isolate you're interacting with when you're an embedder.) It would be good to come up with a concrete list of programs that is problematic without an explicit context. Then those use cases can inform our design decisions.

**Comment by mahesh-hegde** [comment]
Main reason I am thinking this is I'd like to see local references supported first class. We want to provide a scoped API in that case.

Here by __context__ I mean some structure having the JNI pointers, including VM, class loader, and other state (eg: use local reference vs global reference), and not Application / Activity context.

Due to nature of threads being somewhat abstracted in Dart, I think it's better if Dart code has this pointer and passes it to C. But as far as user sees it, it can be completely optional with a default behavior. Eg: we can treat a NULL as default context in the C layer.

**Comment by mahesh-hegde** [comment]
I am brainstorming what are possible designs for a local-reference API. Assuming we use push/pop local frame mechanism.

I will use the word `frame` instead of `context` to avoid confusion with other types of contexts we have in Flutter / Android. In implementation, this will probably just indicate whether to allocate references globally or locally, since frame is more like stack frame in JNI (not arena) and thus we can't really have frame references.

1. similar to `using`

```dart
// Usage
usingFrame((frame) {
  var a = A.factory(context: frame, arg1, arg2);
  var b = new B(context: frame, arg);
  var c = a.getProperty()
  c.doSomething()
})

/// Implementation of `usingFrame` omitted.
```

There are still some choices to make:
  - let `a` be a variable in local frame. if we call `a.getProperty()` which returns a JNI object, should the returned object be in local frame or global frame, if no frame is explicitly specified?

This is most similiar to current `using` API in FFI and requires least work on our part.

But the problem is async context switches. With using push/pop frames API, (which I think is natural way to handle this in JNI), we can't register a destructor function for individual objects. If there's an async call, and some other function using JNI starts executing, that function will erroneously use the frame we allocated and even ends up popping it.

Another problem is passing frame manually to each JNI function is error prone. You forget something and conceptually at least, it allocates a global ref instead. It will be taken care of by NativeFinalizer but that's still not desired behavior.

2. `usingFrame` but set a global frame in `package:jni` on entry, and unset on exit

```dart
// Usage
usingLocalReferences({
    var a = A.factory(arg1, arg2);
    var b = new B(arg);
    var c = a.getProperty()
    c.doSomething()
})

// Implementation
T usingLocalReferences<T>(T Function() callback) {
    var oldReferenceType = referenceType;                             // global, we may want to use zones if that's more appropriate
    referenceType = ReferenceType.localRefs;
    jniEnv.pushLocalFrame(...., ...);
    result = callback();                                                              // Exception handling omitted for clarity
    jniEnv.popLocalFrame(..., ....);
    referenceType = oldReferenceType;
    return result;
}
````

This still has the problem of async context switches, but at least a little nicer to write for user.

I think the problem of async context switches can't be easily solved by the push/pop API, because

  1. We can't specify a specific frame to pop, it just pops the last frame
  2. Async callbacks complete out of order and end up using & popping different frames.
