### ISSUE TITLE
Pick up argument names from the sources

### ISSUE THREAD

**Issue by mit-mit** [dart-lang/jnigen#187]
Currently we generate something like this:
```
/// from: public void <init>(java.util.Set set, androidx.health.connect.client.time.TimeRangeFilter timeRangeFilter, java.util.Set set1)
  AggregateRequest(Set set0, TimeRangeFilter timeRangeFilter, Set set1)
      : super.fromRef(
            _ctor(set0.reference, timeRangeFilter.reference, set1.reference)
                .object);
)
```

It would be great if we could pick up all the argument names (e.g. `metrics` and `dataOriginFilter`) from the source code:
```
public AggregateRequest(
    @NonNull Set<@NonNull AggregateMetric<@NonNull ?>> metrics,
    @NonNull TimeRangeFilter timeRangeFilter,
    @NonNull Set<@NonNull DataOrigin> dataOriginFilter

```

**Comment by mahesh-hegde** [comment]
It's possible the bindings you are looking at are generated from JARs and not source. In JARs parameter name information is erased (unless compiled with debug options).

**Comment by mit-mit** [comment]
@mahesh-hegde, what PR/commit was this completed in?

**Comment by HosseinYousefi** [comment]
Let's reopen this. Not because there needs to be any extra work done to support it. But because we want to have a nicer way to automatically include the name information when generating .jar files from gradle.

**Comment by mahesh-hegde** [comment]
Apologies I didn't understand the issue properly. Is this Java or Kotlin?

**Comment by HosseinYousefi** [comment]
Both. The issue itself is with the fact that .jar files erase the name information. So as you correctly identified, this is not an issue with JNIgen, but with the way that we obtain these .jar files. The open question here, is that can we get the .jar files with naming informations from Maven and gradle or not?

**Comment by mahesh-hegde** [comment]
In case of android, you may want to try changing `releaseCompileClasspath` and `debugCompileClasspath` in the gradle stub. There maybe an equivalent flag to standalone kotlin compiler.

**Comment by mahesh-hegde** [comment]
If source is in the plugin / app project itself, the closest I could find is to use the method in [this StackOverflow answer](https://stackoverflow.com/a/22183825/17285857)

and add flag `-parameters` to javac.

There may be a kotlin equivalent.

The ones you download from maven / google repos do not have this, and we don't have control over that.

**Comment by HosseinYousefi** [comment]
We could download `xyz-sources.jar` for the libraries that include it. [See this for maven](https://stackoverflow.com/questions/11361331/how-to-download-sources-for-a-jar-with-maven).

A lot of the libraries have the sources uploaded as well, this is what IDEs use to provide rich autocompletion and javadocs, we could use the same mechanism to generate the argument names.

**Comment by HosseinYousefi** [comment]
Closing as we support downloading sources in both Maven and Gradle: https://github.com/dart-lang/jnigen/commit/68a9dc7ec6f5620a519326402aec436b8144b8ba

**Comment by mit-mit** [comment]
fyi @mariamhas, I think this might make the healthconnect sample a lot better?

**Comment by HosseinYousefi** [comment]
> fyi @mariamhas, I think this might make the healthconnect sample a lot better?

Will open a PR for flutter/samples with the update. 0.5.0 also has `Set` and `Long` readily available, so it'll improve the sample quite a bit.
