### ISSUE TITLE
Is README too complex?

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#210]
I think `README` file may be intimidating to new users.

I think showing generated C bindings etc.. is not needed.

First we should lead with how user can generate bindings for their own classes or jars.

We want to convey these things:

1. There's only 3 required parameters:
    * Input: source paths / class paths / other dependency specifications
    * Output: target file / directory
    * class/package names

2. Once you generate the bindings, the bindings work as long as you can find same classes in classpath. You don't need to use same JARs or build system.

3. It may be better to first give an example of dart-only bindings. C Bindings are hard to setup. Whereas with dart-only bindings user can create a flutter package and start adding jnigen config.

**Comment by seifibrahim32** [comment]
I am ready to help mentors for desktop issue , I found a way

**Comment by seifibrahim32** [comment]
@HosseinYousefi

**Comment by Karan741187** [comment]
> I think `README` file may be intimidating to new users.
> 
> I think showing generated C bindings etc.. is not needed.
> 
> First we should lead with how user can generate bindings for their own classes or jars.
> 
> We want to convey these things:
> 
> 1. There's only 3 required parameters:
>     * Input: source paths / class paths / other dependency specifications
>     * Output: target file / directory
>     * class/package names
> 
> 2. Once you generate the bindings, the bindings work as long as you can find same classes in classpath. You don't need to use same JARs or build system.
> 
> 3. It may be better to first give an example of dart-only bindings. C Bindings are hard to setup. Whereas with dart-only bindings user can create a flutter package and start adding jnigen config.

Sir I'm new to open source and would like to contribute on this issue.
I've done basics of dart and flutter as well.

**Comment by HosseinYousefi** [comment]
You can try! It's mostly about the documentation.

**Comment by Karan741187** [comment]
Thankyou sir

**Comment by mahesh-hegde** [comment]
@Karan741187 this may be a little complicated for you, because the details (especially Java) involved can be overwhelming for a beginner. I will be picking this up.

**Comment by Karan741187** [comment]
Well I'm done with Java as well but it's ok if you wish to continue

**Comment by mahesh-hegde** [comment]
Look at the changes in current PR. That particular changes (such as FAQs) required knowing some project-specific stuff.

But you are welcome to improve the documentation always. :)

**Comment by Karan741187** [comment]
Ok sir
