### ISSUE TITLE
Adding new Example for Windows with the other 4 examples 

### ISSUE THREAD

**Issue by seifibrahim32** [dart-lang/jnigen#244]
Can I fork this jnigen repo to add helpful documentation for Windows.?

**Comment by HosseinYousefi** [comment]
We don't necessarily need this.

You can of course create another repo with jnigen examples for windows, write blog posts, etc.

**Comment by HosseinYousefi** [comment]
Every example inside the repo is going to add to the total time of the CI and will have to be maintained. For now we don't have such a need, the example could be in a different repo.
