### ISSUE TITLE
Not releasing the `_classRef` inside the classes.

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#252]
We currently generate `static final _classRef = jniAccessors.getClassOf(...)`. We don't release these classes. We should instead use `findJClass` for them to be `Finalizable`.

**Comment by mahesh-hegde** [comment]
I think `static` fields never go out of scope from the view of GC ?

It's a conscious decision to keep them forever once loaed, at least for now. IIRC Even android JNI page recommends keeping some class refs around. (Hopefully there won't be millions of them :P).

You may come up with a more complex mechanism if you wish. Keep in mind looking up classes and method IDs is relatively costly too.

As for methodIDs, they are not JNI references. Their lifetime is bound to `jclass` from which they are obtained.

**Comment by HosseinYousefi** [comment]
From what we discussed with @mahesh-hegde:

Android creates a VM per process, so it doesn't matter for Android.
For other platforms though, does Dart GC the classes at termination? So would `Finalizable` things get finalized?

@dcharkes Do you know this?

**Comment by dcharkes** [comment]
On isolate group shutdown all `NativeFinalizer`s attached to all `Finalizable`s in the heap are run.

Here's a test illustrating the behavior: https://dart-review.googlesource.com/c/sdk/+/236320/21/tests/ffi_2/vmspecific_native_finalizer_isolate_groups_test.dart

VM shutdown (unless `exit` is called) shuts down all isolate groups.

**Comment by mahesh-hegde** [comment]
Well in that case migrating `_classRef` to a finalizable type makes sense.

One concern is it's not possible to implement equivalent semantics in C, because dll is shared by all isolates in a process.

**Comment by HosseinYousefi** [comment]
> One concern is it's not possible to implement equivalent semantics in C based bindings, because dll is shared by all isolates in a process.

In the dart only bindings it's possible to create a lot of isolates (for example via compute), call Java methods, and shut down these temporary isolates, and since they're not finalizable now, it leaks global refs to the same `jclass`.

But since in C based bindings, we at least have the shared global ref, it's not as big of a deal because we won't have so many class refs anyways.
