### ISSUE TITLE
Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT)

### ISSUE THREAD

**Issue by asadamatic** [dart-lang/jnigen#286]
I was trying the example, from [this tutorial](https://dart.dev/guides/libraries/java-interop). I'm stuck at this error while running `dart run` command, and I haven't found any `dart` and `jnigen` solutions for it.

**Command**

```
dart run jni:setup -p jni -s src/interop_practice
```

**Error**
```
selecting source directories: [src/interop_practice, /Users/asadamatic/.pub-cache/hosted/pub.dev/jni-0.4.0/src]
+ [.dart_tool/jni/jni_native_build_ZevUMA] cmake /Users/asadamatic/Desktop/interop/interop_practice/src/interop_practice
-- The C compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Java: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java (found version "11.0.15") 
-- Configuring incomplete, errors occurred!

CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
  CMakeLists.txt:29 (find_package)



Command exited with status code 1
+ [.dart_tool/jni/jni_native_build_ZevUMA] cmake --build .

make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.

Command exited with status code 2
+ [.dart_tool/jni/jni_native_build_6crPF2] cmake /Users/asadamatic/.pub-cache/hosted/pub.dev/jni-0.4.0/src
-- The C compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Java: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java (found version "11.0.15") 
-- Configuring incomplete, errors occurred!

CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 AWT)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)



Command exited with status code 1
+ [.dart_tool/jni/jni_native_build_6crPF2] cmake --build .

make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.

Command exited with status code 2
```

**Jnigen.yaml**

```
output:
  c:
    library_name: example
    path: src/interop_practice/
  dart:
    path: lib/interop_practice.dart
    structure: single_file

source_path:
  - 'java/'
classes:
  - 'dev.dart.Example'
```

**Comment by mahesh-hegde** [comment]
Problem seems to be with your java setup.

> -- Found Java: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java (found version "11.0.15") 

Try installing standalone JDK (through homebrew, since you appear to be using macos), and try again. (Maybe you need to set JAVA_HOME also.)

**Comment by asadamatic** [comment]
I have jdk installed on my system and this is the result of `java --version` 

```
openjdk 11.0.15 2022-04-19
OpenJDK Runtime Environment (build 11.0.15+0-b2043.56-8887301)
OpenJDK 64-Bit Server VM (build 11.0.15+0-b2043.56-8887301, mixed mode)
```

**Comment by mahesh-hegde** [comment]
Exactly my point. This JDK is from android studio. Try with a fresh JDK installation from homebrew other OpenJDK distribution channels.

**Comment by asadamatic** [comment]
Okay, I'll try that.

**Comment by asadamatic** [comment]
Result of `brew install java` an `brew install openjdk` 
```
Warning: openjdk 20.0.1 is already installed and up-to-date.
To reinstall 20.0.1, run:
brew reinstall openjdk
  ```
  
  Its strange because on `java --version` it gives the version `11.0.5`

**Comment by HosseinYousefi** [comment]
> Its strange because on `java --version` it gives the version `11.0.5`

Try setting `JAVA_HOME` to the path of openjdk, also I believe (see #285) it's better if you use a lower version of open-jdk like 17 instead until we fix the issues with the higher versions.

**Comment by mahesh-hegde** [comment]
> Result of brew install java an brew install openjdk

If I remember, brew gives different versions like `openjdk@11`. In that case brew might print some additional commands which you have to run.

---

The problem here is

* Your JAVA_HOME points to android studio JDK.

* You're trying to run an example on standalone, which calls CMake.

* CMake looks for JNI headers, it's not there with android studio JDK.

* So CMake can't build standalone support library.

So try with a desktop-oriented installation of JDK and let us know how it goes.

**Comment by asadamatic** [comment]
@HosseinYousefi `JAVA_HOME` is already set to jdk that resides inside of Android Studio. I'll try to downgrade it.

**Comment by asadamatic** [comment]
@mahesh-hegde I'll try it.

**Comment by HosseinYousefi** [comment]
> @HosseinYousefi `JAVA_HOME` is already set to jdk that resides inside of Android Studio. I'll try to downgrade it.

Try setting it to the one that brew installed instead.

**Comment by HosseinYousefi** [comment]
@asadamatic Is your problem fixed now?

**Comment by asadamatic** [comment]
I'll try this on weekend.

**Comment by asadamatic** [comment]
> > @HosseinYousefi `JAVA_HOME` is already set to jdk that resides inside of Android Studio. I'll try to downgrade it.
> 
> Try setting it to the one that brew installed instead.

@HosseinYousefi I tried it. Now it gives the following error `Could NOT find JNI (missing: AWT JVM)`


### Logs
```
-- Found Java: /usr/local/opt/openjdk/bin/java (found version "20.0.1") 
-- Configuring incomplete, errors occurred!

CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: AWT JVM)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)


```

**Comment by HosseinYousefi** [comment]
> > > @HosseinYousefi `JAVA_HOME` is already set to jdk that resides inside of Android Studio. I'll try to downgrade it.
> 
> > 
> 
> > Try setting it to the one that brew installed instead.
> 
> 
> 
> @HosseinYousefi I tried it. Now it gives the following error `Could NOT find JNI (missing: AWT JVM)`
> 
> 
> 
> 
> 
> ### Logs
> 
> ```
> 
> -- Found Java: /usr/local/opt/openjdk/bin/java (found version "20.0.1") 
> 
> -- Configuring incomplete, errors occurred!
> 
> 
> 
> CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
> 
>   Could NOT find JNI (missing: AWT JVM)
> 
> Call Stack (most recent call first):
> 
>   /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
> 
>   /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
> 
>   CMakeLists.txt:32 (find_package)
> 
> 
> 
> 
> 
> ```

The version seem to be 20. Please downgrade to 17 or lower.

**Comment by asadamatic** [comment]
Okay, I'll try that

**Comment by asadamatic** [comment]
@HosseinYousefi I downgraded to `openjdk17` and change the `JAVA_HOME` path to this. version, but I'm still gettting this error `Could NOT find JNI (missing: AWT JVM)` 

### Logs
```
-- The C compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Java: /usr/local/opt/openjdk@17/bin/java (found version "17.0.7") 
-- Configuring incomplete, errors occurred!

CMake Error at /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find JNI (missing: AWT JVM)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.26.4/share/cmake/Modules/FindJNI.cmake:569 (find_package_handle_standard_args)
  CMakeLists.txt:32 (find_package)



Command exited with status code 1
+ [.dart_tool/jni/jni_native_build_7XSbiq] cmake --build .

make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.
```

**Comment by mahesh-hegde** [comment]
This might be leading you the wrong way, but which path did you set the JAVA_HOME to?

It should be something like /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Home

This JAVA_HOME folder should contain include/ directory, which contains JNI headers.

**Comment by asadamatic** [comment]
I had previously set it to `/usr/local/opt/openjdk@17`, and it worked after changing it to, 
```/usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home```. 

@HosseinYousefi @mahesh-hegde  Thanks for helping me out on this.

**Comment by asadamatic** [comment]
Even though I'm still not able to run the example, this part of my problem is fixed.
