### ISSUE TITLE
Either remove or expose `-r` flag

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#299]
`ApiSummarizer.jar` has a `-r` flag which recursively includes the dependencies of the classes. This however is not exposed through `jnigen.yaml` and one has to manually add it in `summarizer > extra_args`. We should either remove the functionality or expose it in the config.

**Comment by mahesh-hegde** [comment]
I believe it's better to remove it.

Because this works at Java code level, and probably pulls in dependencies of excluded classes / methods too. As we add exclude / include configuration, this might become a conflicting behavior.
