### ISSUE TITLE
Use Kotlin's metadata in binding generation

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#300]
In certain cases, some of the method names in the bytecode produced from Kotlin, has hyphen in it. Of course, Dart's methods cannot be hyphenated (and it's a wrong name). 

For this and other issues regarding Kotlin jars, we need to use the metadata provided.

**Comment by HosseinYousefi** [comment]
APISummarizer can use https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-metadata-jvm

**Comment by Marco4763** [comment]
@HosseinYousefi can i share a link here to an article i wrote as feedback from my interaction with jnigen?

**Comment by HosseinYousefi** [comment]
> @HosseinYousefi can i share a link here to an article i wrote as feedback from my interaction with jnigen?

Is it related to this specific issue? You can share it!

**Comment by Marco4763** [comment]
@HosseinYousefi is not related to this issue, I have created a new issue #302.

**Comment by HosseinYousefi** [comment]
We're now using the metadata. #313 Tracks the specific features to be added.
