### ISSUE TITLE
Add support for pub global activate

### ISSUE THREAD

**Issue by chashkovdaniil** [dart-lang/jnigen#307]
Hi! Thank you for this package🏆

I use this package to interact with java code.
I have scripts in the bin folder that are run with the "dart pub global run command".
After executing the command, it says to me: "as globally activated requires the Flutter SDK, which is unsupported for global executables."
Is there any way to decouple jnigen from using flutter ?

**Comment by chashkovdaniil** [comment]
I'm sorry, it's not in this package that you need to remove the dependency on flutter, but in jni

**Comment by chashkovdaniil** [comment]
https://github.com/chashkovdaniil/jnigen/pull/1/files

**Comment by HosseinYousefi** [comment]
> Is there any way to decouple jnigen from using flutter?

Currently, `package:jni` is coupled with Flutter solely to build its native dependencies. There is an issue tracking this: #245.
