### ISSUE TITLE
"No podspec found" when building on macos

### ISSUE THREAD

**Issue by alhafoudh** [dart-lang/jnigen#317]
Hi,
I am tring to get JNI working on macos. I ran `dart run jni:setup` and `dart run jnigen:setup` successfully, but when I try to build the app on macos I get following podspec errors and the app does not build.

```
Launching lib/main.dart on macOS in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
      Using `ARCHS` setting to build architectures of target `Pods-RunnerTests`: (``)

    Finding Podfile changes
      A myapp
      A jni
      - FlutterMacOS

    Fetching external sources
    -> Fetching podspec for `FlutterMacOS` from `Flutter/ephemeral`
    -> Fetching podspec for `myapp` from `Flutter/ephemeral/.symlinks/plugins/myapp/macos`
    [!] No podspec found for `myapp` in `Flutter/ephemeral/.symlinks/plugins/myapp/macos`

Exception: Error running pod install
```

**Comment by HosseinYousefi** [comment]
We still don't support Flutter Mac apps: #41

That said, your error seems odd, make sure you have a macos directory and a `Podfile` within that (`flutter create .` creates it for you).

**Comment by alhafoudh** [comment]
Thank you for pointing me to #41, it makes sense now.

I have Podfile in my macos directory, but the error looks like it required `myapp.podspec` file :-/. Weird.

**Comment by HosseinYousefi** [comment]
Closing in favor of #41.
