### ISSUE TITLE
Does jnigen supports "call flutter code from android-side"?

### ISSUE THREAD

**Issue by Raonshi** [dart-lang/jnigen#318]
Hi. I've got a question about jnigen.

I saw many examples which "calling android functions from flutter-side", but there is no case about "calling flutter function from android-side".

Actually this process can be made using MethodChannel, but MethodChannel only supports "Async" job.
Unfortunately, I need "Sync" job.

So..
Is jnigen supports "Calling flutter function from android-side"?

**Comment by dcharkes** [comment]
I believe you are asking for:

* https://github.com/dart-lang/jnigen/issues/65

or:

* https://github.com/dart-lang/jnigen/issues/70

**Comment by Raonshi** [comment]
@dcharkes 

hmm... maybe not.

I'll give you some basic code to explain my case.


- Android Side(Kotlin)
```kotlin

fun getStatus(): Int {
    // call dart function and returns the value.
    val result = FlutterPlugin.currentStatus()
}
```

- Dart Side

```dart
class FlutterPlugin {
    int currentStatus() => 1;
}
```

**Comment by HosseinYousefi** [comment]
> ```kotlin
> fun getStatus() {
>     // call dart function and returns the value.
>     val result = FlutterPlugin.currentStatus()
>     print(result) // result muse be 1
> }
> ```

#70 will add this functionality but you need to modify your code like so:

```kotlin
fun getStatus(currentStatus: Callable<Int>) {
    // call dart function and returns the value.
    val result = currentStatus();
    print(result) // result muse be 1
}
```

And then call the getStatus from Dart:

```dart
kotlinObject.getStatus(
  Callable.type(T).implement(
    call: FlutterPlugin().currentStatus,
  ),
);
```

**Comment by Raonshi** [comment]
@HosseinYousefi 

Ah, My explaining was lacking.
The `getStatus()` function will be called from other platforms automatically. That is why i asked this question.
Because of above reason, I can use Callable as a parameter.

```kotlin
// This function is called by other platform per each frame.
// So, parameter must be none.
fun getStatus() {
    // call dart function and returns the value.
    val result = FlutterPlugin.currentStatus()
    print(result) // result muse be 1
}
```

I think this concept is impossible. right? (if not, please help me. i don't have any ideas)

**Comment by HosseinYousefi** [comment]
> The `getStatus()` function will be called from other platforms automatically.

The callable can still be called from the native side automatically/whenever it wants. The point is you need to provide what should be called once at the beginning. 

I don't see a scenario where passing a callable won't work for you actually. 

In any case `jnigen` generates Java/Kotlin bindings for Dart and **not** Dart bindings for Java/Kotlin.

**Comment by HosseinYousefi** [comment]
> @HosseinYousefi
> 
> `getStaus()` will be called by other platform. (sorry. i can't explain this platform because it is related with business) this platform used other services (such as web, other application, etc), and `getStatus()` is reused those services.
> 
> that is why i can not use `Callable` parameter in `getStatus()`.

You don't have to necessarily pass the Callable to `getStatus` itself. That was just an example. For example you could create a function called `initCallable` that accept the callable you'll need from Dart.

```kotlin
class FlutterPlugin {
  companion object {
    var currentStatusCallable : Callable<Int>
    fun currentStatus() -> Int {
      return currentStatusCallable.call()
    }
  }
}

fun initCallable(callable: Callable<Int>) {
  FlutterPlugin.currentStatus = callable;
}
```

Now `getStatus` can simply call `FlutterPlugin.currentStatus()`. And you'll need to call `initCallable` after first running your application.

```dart
initCallable(
  Callable.type(JInteger.type).implement(
    call: () => FlutterPlugin().currentStatus().toJInteger(),
  ),
);
```

**Comment by Raonshi** [comment]
@HosseinYousefi 
I tried your solution, But there is no `Callable` type in Dart.

**Comment by Raonshi** [comment]
there is no `implement` method in Callable class. so, I made my own callable("FlutterCallable") class which inherit Callable class.

```kotlin
// Kotlin Side
class FlutterPlugin {
    companion object {
        lateinit var currentStatusCallable: FlutterCallable<Int>
        fun currentStatus(): Int {
            return currentStatusCallable.call()
        }
    }

    fun initCallable(callable: FlutterCallable<Int>) {
        FlutterPlugin.currentStatusCallable = callable
    }
}

class FlutterCallable<T> : Callable<T> {
    private var callable:(() -> T)? = null;

    fun implement(call: () -> T ){
        callable = call
    }

    override fun call(): T {
        return callable!!()
    }
}
```

```dart
// Dart Side
FlutterCallable<JInteger> callable = FlutterCallable(T: JInteger.type);
callable.implement(
  (() => JInteger(1)) as JObject, // I want to know how can i cast Function to JObjcet
);

plugin.initCallable(callable);
```

But I can not find a way to casting `int Function()` to `JObject`

**Comment by HosseinYousefi** [comment]
This is not available yet. After #70 lands. You'll be able to do it.
