### ISSUE TITLE
Test the matrix of [`dart_only`/`c_based`] x [`asm`, `doclet`]

### ISSUE THREAD

**Issue by HosseinYousefi** [dart-lang/jnigen#320]
#319 Happened because we were not testing the ASM backend for `simple_package`. We should test the matrix of [`dart_only`/`c_based`] x [`asm`, `doclet`].

**Comment by mahesh-hegde** [comment]
Do we still need this, if we can verify summary is same for both?

Bindings are a function of summary, so if there's disrepancy, it should be addressed in API summary.

I think combinatorial explosion would not be required.

**Comment by dcharkes** [comment]
Agreed. If we have sufficient test coverage of the summarizers, we don't need to do the integration tests with both backends! 👌
