### ISSUE TITLE
desktop build

### ISSUE THREAD

**Issue by yalda-student** [dart-lang/jnigen#333]
Hi. First, thank u for this package.  I have a test project, a code that connects to a socket in kotlin language. when I execute below command on mac everything was ok, but in Windows in failed (of course I use `flutter build apk` in both OS):
`dart run jnigen --config jnigen.yaml` 
failure message:
```
gradle exited with status 1
. This can be because the Android build is not yet cached. Please run `flutter build apk` in .\ and try again

#0      AndroidSdkTools._runGradleStub (package:jnigen/src/tools/android_sdk_tools.dart:207:7)
#1      AndroidSdkTools.getGradleClasspaths (package:jnigen/src/tools/android_sdk_tools.dart:144:7)
#2      getSummary (package:jnigen/src/summary/summary.dart:140:34)
#3      generateJniBindings (package:jnigen/src/generate_bindings.dart:29:21)
<asynchronous suspension>
#4      main (file:///C:/Users/yalda_student/AppData/Local/Pub/Cache/hosted/pub.dev/jnigen-0.5.0/bin/jnigen.dart:17:3)
<asynchronous suspension>
```

but despite this error, when I build Android everything is normal, but in the desktop build,  it throws the following error:

```
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library 'my_test.dll': error code 126

When the exception was thrown, this was the stack: 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      ProtectedJniExtensions.initGeneratedLibrary (package:jni/src/jni.dart:296:31)
#3      jniLookup (package:tor_test/example.dart:25:28)
#4      jniLookup (package:tor_test/example.dart)
#5      MyTest._ctor (package:tor_test/example.dart:39:7)
#6      MyTest._ctor (package:tor_test/example.dart)
#7      new MyTest (package:tor_test/example.dart:45:27)
```

can anyone help me?

**Comment by HosseinYousefi** [comment]
What version of jnigen are you using?

**Comment by yalda-student** [comment]
yeah, they are the latest ones. Should I install the previous versions? I also installed LLVM, cmake, and maven but nothing changed.
Thank you so much; I thought I have done it incompletely.

**Comment by HosseinYousefi** [comment]
Have you added `%JAVA_HOME%\bin\server` to your path? https://github.com/dart-lang/jnigen#java-tooling

**Comment by yalda-student** [comment]
yes. I added it to path variable in system variables but it wasn't effective :(
executing `dart run jni:setup -p jni -s ./src` commend wasn't failed.

**Comment by HosseinYousefi** [comment]
Code 126 usually happens because of the missing a dll dependency. If you have recently added the path to `jvm.dll`, you might want to restart your computer once. 

`dart run jni:setup` will not fail because the its dependency on `jvm.dll` is dynamic.

**Comment by yalda-student** [comment]
yes, I restarted pc multi times.
Now I decided to recreate the project again in windows(before I cloned it from repo). command  `dart run jnigen --config jnigen.yaml` executed successfully. but after running the project I got error again.

```
The following ArgumentError was thrown while handling a gesture:
Invalid argument(s): Failed to load dynamic library 'my_test.dll': error code 126

When the exception was thrown, this was the stack: 
#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      ProtectedJniExtensions.initGeneratedLibrary (package:jni/src/jni.dart:296:31)
```

**Comment by HosseinYousefi** [comment]
I tested it using Zulu Java 11 with path `C:\Program Files\Zulu\zulu-11\bin\server` added to `$env:Path`. And things seem to be working well. 

If your problem persists, you can use [procmon](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) to see why the `.dll` files are not found.

**Comment by mahesh-hegde** [comment]
Another possibility: The CMake invoked by `jni:setup` failed but somehow the failure was not reported.

You should start by checking

1. `my_test.dll` exists in `.\build\jni_libs`.

2. Run `echo $env:Path` in powershell. This should contain your `JAVA_HOME\bin\server`

If both these are true but running still fails, we need to investigate further.

**Comment by yalda-student** [comment]
Hello. Yes, my_test.dll exists in .\build\jni_libs, and` JAVA_HOME\bin\server` was in the system path, but I still got the exception.

**Comment by mahesh-hegde** [comment]
Have you initialized JVM on standalone target?

https://github.com/dart-lang/jnigen/blob/f4fb338af6f97de90a71294a7bed071adf336f97/jnigen/example/pdfbox_plugin/example/lib/main.dart#L43

Something like

```
Jni.spawn(classPath: [/*CLASSPATH entries*/]); // on Flutter Desktop
Jni.spawn(classPath: [/*CLASSPATH entries*/], dylibDir: "build/jni_libs"); // on standalone (non-flutter)
```

**Comment by yalda-student** [comment]
Hello. Thank you for your guid and excuse me for delay. Actually I faced visual studio  error in running desktop app and I couldn't test this solution and I'm still struggling with that error. I will fix that and feedback here. Thanks alot

**Comment by HosseinYousefi** [comment]
Were you able to resolve your issue?

**Comment by HosseinYousefi** [comment]
Closing this for now. Let me know if your issue persists.
