### ISSUE TITLE
Conflicting attributes

### ISSUE THREAD

**Issue by gergovari** [dart-lang/jnigen#342]
I need this workaround for now: 
```
exclude:
  fields:
    - 'com.artifex.mupdf.fitz.LinkDestination#type'
```

**Comment by gergovari** [comment]
#218 should apply here(?), but it doesn't.

**Comment by HosseinYousefi** [comment]
`type` already exists in the set of keywords: https://github.com/dart-lang/jnigen/blob/main/jnigen/lib/src/bindings/renamer.dart#L68

What version of jnigen are you using?

**Comment by gergovari** [comment]
^0.5.0, should be the latest.

**Comment by HosseinYousefi** [comment]
This is solved on the main branch. I will publish 0.6.0 soon, in the meanwhile you can use a git dependency.
