### ISSUE TITLE
ASM vs Doclet backend issues

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#352]
Found some bugs in asm summarizer when implementing #258.

~- [ ] Wildcard type is reported as `DeclaredType`~ - To be implemented along with #141 
- [x] Enum values not contained.
- [x] ASM summarizer reports `public static final char` as `int` instead of `String`.

**Comment by mahesh-hegde** [comment]
Cross link #141 . We can skip this for now if that proves to be tedious.

**Comment by mahesh-hegde** [comment]
Doclet reports `string`, so since doclet is default, its a bug..

**Comment by HosseinYousefi** [comment]
> Doclet reports `string`, so since doclet is default, its a bug..

I meant that I think `int` is correct. So whichever reports `String` is incorrect.
