### ISSUE TITLE
Proper way to create a plugin

### ISSUE THREAD

**Issue by gergovari** [dart-lang/jnigen#355]
What's the proper way to create a plugin?

Specifying dependencies in the app module is not convenient (#351) and including custom Java code is even harder.

**Comment by HosseinYousefi** [comment]
Dart standalone plugin or a Flutter plugin?

**Comment by mahesh-hegde** [comment]
I'd recommend to start with a normal plugin and add pure dart bindings. But you can also follow `notification_plugin` example.

**Comment by gergovari** [comment]
> Dart standalone plugin or a Flutter plugin?

Flutter plugin

**Comment by gergovari** [comment]
> I'd recommend to start with a normal plugin and add pure dart bindings. But you can also follow `notification_plugin` example.

Ahhh, `source_path`, gotchu.

Will try tomorrow.

**Comment by gergovari** [comment]
> I'd recommend to start with a normal plugin and add pure dart bindings. But you can also follow `notification_plugin` example.

Okay, my code works. Gradle can't resolve external Java dependencies though. Where should I specify them?

**Comment by gergovari** [comment]
Figured it out, just add `dependencies` and `repositories` at the root level of your `build.gradle`.

**Comment by mahesh-hegde** [comment]
Try specifying as dep in example's app/build.gradle

        Mahesh
