### ISSUE TITLE
Binding Generation Cause Error (Could not find goal 'assembly' in plugin org.apache.maven.plugins:maven-assembly-plugin:3.6.0)

### ISSUE THREAD

**Issue by MAsadWaseem** [dart-lang/jnigen#377]
I am running this simple command  **"dart run jnigen --config jnigen.yaml"** for the generation of binding 
but getting the error given below.

One key point is that I am running this command in the example code of jnijen.

jnigen_example-main % dart run jnigen --config jnigen.yaml
Building package executable... (1.1s)
Built jnigen:jnigen.
(jnigen) INFO: Building ApiSummarizer component. This might take some time. 
The build will be cached for subsequent runs

(jnigen) INFO: execute mvn --batch-mode --update-snapshots -f /Users/muhammadasadwaseem/.pub-cache/hosted/pub.dartlang.org/jnigen-0.2.0/java/pom.xml assembly:assembly
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.207 s
[INFO] Finished at: 2023-08-29T14:20:43+05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Could not find goal 'assembly' in plugin org.apache.maven.plugins:maven-assembly-plugin:3.6.0 among available goals help, single -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

maven exited with 1
Unhandled exception:
FileSystemException: Deletion failed, path = './.dart_tool/jnigen/target' (OS Error: No such file or directory, errno = 2)
#0      _Directory._delete.<anonymous closure> (dart:io/directory_impl.dart:192:9)
<asynchronous suspension>
#1      buildApiSummarizer (package:jnigen/src/tools/build_summarizer.dart:52:5)
<asynchronous suspension>
#2      buildSummarizerIfNotExists (package:jnigen/src/tools/build_summarizer.dart:75:5)
<asynchronous suspension>
#3      generateJniBindings (package:jnigen/src/generate_bindings.dart:20:3)
<asynchronous suspension>

FYI @HosseinYousefi

**Comment by HosseinYousefi** [comment]
It seems that you're using JNIgen 0.2.0, can you update yours to the latest version?

If you problem continues, paste in your `jnigen.yaml` so I can reproduce the error.

**Comment by MAsadWaseem** [comment]
thanks for your response.
Am using the example that you have provided on GitHub  https://github.com/HosseinYousefi/jnigen_example/tree/main
Also tried with this example "https://github.com/dart-lang/jnigen/tree/main/jnigen/example/in_app_java"
Also tried with the 0.3.0 version but got this error.

I also searched for this mostly they are pointing toward pom.xml
or change your command etc

FYI: I downloaded Maven from this link https://maven.apache.org/download.cgi (Version is 3.9.4 bin.tar ) Add in the path. 
2) Also done with clang format 
(Might be issue due to latest Maven version)

**Doctor summary** (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 13.4 22F66 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.81.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

**Comment by HosseinYousefi** [comment]
The latest published version for both `package:jni` and `package:jnigen` is 0.5.0 right now.

I personally have Maven 3.9.1 with Java 17.0.5.

**Comment by MAsadWaseem** [comment]
Actually am using a bit older version of Flutter so it supports 0.3.0 
If you find any help related to these logs pin me.

thanks @HosseinYousefi

**Comment by HosseinYousefi** [comment]
> Actually am using a bit older version of Flutter so it supports 0.3.0 If you find any help related to these logs pin me.

The issue with newer versions of maven seem to be solved by https://github.com/dart-lang/jnigen/pull/261.

So you should either
1. Downgrade your maven
2. Upgrade your flutter and upgrade jni/jnigen
3. Run `mvn compile --batch-mode --update-snapshots -f /Users/muhammadasadwaseem/.pub-cache/hosted/pub.dartlang.org/jnigen-0.2.0/java/pom.xml` manually. (It's now `compile` instead of `assembly:assembly` apparently).

**Comment by MAsadWaseem** [comment]
okay, I'll try it later because currently am cannot upgrade my Flutter version due to some packages and custom dependencies.
Thanks for your time  really Appreciate and am closing the issue for now
