### ISSUE TITLE
ApiSummarizer.jar should be rebuilt when outdated

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#39]
```
$ dart bin/setup.dart 
ApiSummarizer.jar exists. Skipping build..
```

This should probably check file timestamps or a version number, so that it can rebuild itself when a newer version of this package is fetched.

**Comment by mahesh-hegde** [comment]
https://github.com/dart-lang/jni_gen/blob/a067d0b1ed53acb6202f98bf5c7547cdbcf92c23/jni_gen/lib/src/tools/build_summarizer.dart#L41

**Comment by dcharkes** [comment]
That is surprising. I had to force it in order to make it work when I filed this bug.

**Comment by mahesh-hegde** [comment]
Actually user should never need to run jni_gen:setup manually.
`buildSummarizerIfNotExists` is called in beginning of
generateJniBindings().

        Mahesh
