### ISSUE TITLE
Java references should implement Finalizable and have a NativeFinalizer

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#50]
We could consider adding native finalizers to the Java references so that they automatically get deleted when the Dart object is GCed.

```dart
  testWidgets("Long.intValue() using JniObject", (tester) async {
    final longClass = jni.findJniClass("java/lang/Long");
    final longCtor = longClass.getConstructorID("(J)V");
    final long = longClass.newObject(longCtor, [176]);

    final intValue = long.callIntMethodByName("intValue", "()I", []);
    expect(intValue, equals(176));
  });
  
  // ...

  // At some point `DeleteGlobalRef` is run on `longClass` and `long` Java references.
```

https://api.dart.dev/stable/2.18.0/dart-ffi/Finalizable-class.html

* `delete` would cancel the native finalizer.

I'm not sure if this should always be generated like this or not. @liamappelbe, we also generate `NativeFinalizer`s for ObjectiveC bindings in ffigen. What is your experience?

**Comment by liamappelbe** [comment]
My experience is that NativeFinalizers are great :)

The only weird thing is testing them, but calling `Dart_ExecuteInternalCommand("gc-now")` via FFI works well. That's what I do in [this test](https://github.com/dart-lang/ffigen/blob/master/test/native_objc_test/automated_ref_count_test.dart).
