### ISSUE TITLE
Typed array accessors

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#69]
Currently accessible through `Jni.env` methods, however we should create a better API.

Likely, we would want an API similar to:

* https://api.dart.dev/dev/2.19.0-240.0.dev/dart-ffi/Pointer-class.html
* https://api.dart.dev/dev/2.19.0-240.0.dev/dart-ffi/Array-class.html

API features:

* `[]` and `[]=`
* Nesting (e.g. `int[][][]`)

**Comment by dcharkes** [comment]
If we would like to _really_ optimize array access, we might need VM support.

The most optimized path:

* call `GetPrimitiveArrayCritical`, which stops the JVM GC.
* access/manipulate data a la `ExternalTypedData`.
* call `ReleasePrimitiveArrayCritical` which allows the JVM GC to run again.

However, the contract with that is quite strict:

> After calling GetPrimitiveArrayCritical, the native code should not run for an extended period of time before it calls ReleasePrimitiveArrayCritical. We must treat the code inside this pair of functions as running in a “critical region.” Inside a critical region, native code must not call other JNI functions, or any system call that may cause the current thread to block and wait for another Java thread.

This would lead to issues if we have other isolates also JNI calls.

So, we should probably implement the "slow" / "indirect" / "non-locking" API first, and worry about optimizing the very-fast-case later when the need arises.

**Comment by mahesh-hegde** [comment]
Thoughts regarding user facing API

I think there are 2 distinct but overlapping use cases here.

1. Using normal APIs which need object arrays, eg: `String[]` in SQLite and others.
2. Sharing memory with java code, with primitive type arrays and byte buffers.

There should be easier API for (1). But a more rigorous API for (2) using typed_data, which provides superset of (1)s functionality.
