### ISSUE TITLE
Generate parameterized methods with erasure equivalents

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#73]
Currently generic methods are skipped. Before #66 is implemented, it should be still possible to achieve an easier middle ground by calling the method without particular generic type.

* Parameterized types should be exposed without type params
* type params in methods should be mapped to their erasure as defined in the JLS.

For example

```
List.get() -> Object
List.set(int, Object)
```

**Comment by dcharkes** [comment]
@mahesh-hegde you self-assigned this. Is there some WIP on this? Or can @HosseinYousefi take a look at this if he's going to take a look at #66? (Since array support also has generics in the API, we might as well take a look at this now, so that we get all generics in the Dart API right.)

**Comment by mahesh-hegde** [comment]
Sorry no WIP. Feel free to reassign.

I thought it would be easy to add the `Erasure` of a generic type parameter in summary output. JLS defines Erasure rigorously (some 4-5 cases).

This is the step before implementing generics.

It's probably an impl choice whether to include Erasure with each `TypeVariable`, or only `TypeParameter` and map from type variable based on scope.
