### ISSUE TITLE
Support runtime visible Annotations

### ISSUE THREAD

**Issue by Wdestroier** [dart-lang/jnigen#79]
Many libraries require the addition of annotations to classes to work. Especially Springboot and the Spring ecosystem.

**Comment by mahesh-hegde** [comment]
Hi, we are far from supporting spring boot and the like.

Currently methods, fields, constructors and to some extent, exceptions are supported. You can see some examples in the `example/` folder.

Even supporting callbacks into dart is really hard in JNI.

------------------------------------------------------------------

Just to give you an idea of the complexity of the problem;

I have briefly used spring boot, and if I recall correctly, most of the annotations are on class methods and parameters.

If you want to annotate a dart "servlet" class like this

```
class Server {
    @Get("/users/{id}")
    User getUser(int id) {}
}
```

First we have to generate a java class mirroring this dart class with appropriate runtime annotations in place. For that you should either generate a class using bytecode, or generate & compile java code then include it in classpath. This requires you to process dart code in addition to java library code. (to read annotations).

That's just half of the story. Spring has to call the methods of your class. Spring is the _framework_ into which your application classes plug and not a library you call from `public static void main`. It has it's own initialization logic etc.. (It might be possible to embed spring boot, but that won't be pleasant.)

However if you want to use underlying libraries like `vert.x`, it might be possible in future with callback support. I am not sure that you would prefer that over the C/C++ FFI equivalent, though.

The main purpose of jnigen as it stands now is interoperating with platform APIs and glue java code. You can look at the examples in `example/` directory.
