### ISSUE TITLE
Create a tool/generate_idefiles.dart

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/jnigen#81]
It is nice to have a script in `tool/` that just creates the `compile_commands.json` for the `src/` folder. That would mean devs on this package don't have to do it manually.

For example [We have one in the Dart SDK](https://github.com/dart-lang/sdk/blob/main/tools/generate_idefiles.py) (but its in python rather than dart for historical reasons).

**Comment by mahesh-hegde** [comment]
Does VSCode auto generate this file? I also didn't observe before but there doesn't need to be a compile_commands.json for VSCode.

**Comment by mahesh-hegde** [comment]
So there are 2 ways to generate clang compile_commands.json.

1. __Using CMake:__ - requires generator be `ninja` or `Unix Makefiles` and the generator has to be actually installed on the system. So this doesn't work on windows.
2. __Using bear:__ - requires bear command installed. Doesn't seem to be available for windows.

And anyway VSCode seems to work without it.
