### ISSUE TITLE
clang-format generated C bindings

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#84]
It's a good idea if generated bindings are formatted consistently.

In theory we can run `clang-format` on generated .c file once in the generator.

In practice user may open the file in an editor with auto format (Eg VSCode with C++ plugin). Then it will reformat the file. (Yes user should not edit the generated file. But one might open the file and press Ctrl+S out of habit, which will reformat.)

Is it a good idea to copy the `.clang-format` file from `jni` package into generated c bindings folder, and format according to that?

**Comment by mahesh-hegde** [comment]
@dcharkes

#### Approach 1: Do not format generated bindings
++ No requirement of clang-format tool
-- No consistent formatting

#### Approach 2: Format using default config
++ No config file required
-- Mismatch with config used by dart SDK and package:jni
-- Requires clang-format on user's end.

#### Approach 3: Copy .clang-format from `jni` into generated code directory.
++ Consistent with other packages
-- Requires clang-format on user's end.

**Comment by dcharkes** [comment]
How about we try if we find `clang-format` and then use it, if we don't find it we output a warning but still continue.

Since we generate the code we could dictate the formatting. Do we need to copy the `.clang-format` file in, or can we pass clang-format a config file with an argument?

**Comment by dcharkes** [comment]
Yeah that's true.

I wouldn't mind having a config file. I think it is good practise to specify the way code should be formatted, such file does exactly that.

If anyone later on doesn't like it, we can always add a config option to not generate the the formatting file.
