### ISSUE TITLE
Use mutex around method / field lookup

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#85]
In current state, loading fields / methods can cause race condition if same MethodID or class is loaded from 2 isolates, and not initialized at the time of checking. It's rare but possible.

Option 1. Leave as it is, it's rare case and at worst may leak a reference.

Option 2: Have a common mutex for lookups.
```
inline load_class(jclass *cls, char *name) {
    if (*cls== NULL) {
        //grab common mutex using platform-specific primitive
        if (*cls== NULL) { // double check, because by the time lock is obtained, it may be initialized by the time we get lock.
           *cls = findClass(name);
        }
        //release mutex
    }
}
```

Option 3: Same as the above but Instead of common mutex, have a mutex per class variable.

cc: @dcharkes @liamappelbe

**Comment by dcharkes** [comment]
I think option 1 is fine for the time being.

But we should add a section to the readme detailing that multiple isolates is only safe if the isolates are not racing in the way you describe.

**Comment by mahesh-hegde** [comment]
I suppose this is changing one or two inline functions / macros, so can be marked for v0.2 or v0.3.
